   - name: StartHTTPD
     service: name={{apache_pkg}} state=restarted
   - name: TestHTTPD
     shell: curl http://{{apache_fqdn}}
     register: result
   - name: DisplayResult
     debug: var=result
